### ISSUE TITLE
Not able to execute

### ISSUE THREAD

**Issue by sshah135** [bhavik001/TxtToHTML#1]
HI Bhavik,

when I try the command it says it is not able to find the express module
Maybe you need to add that in the package .json file

For your reference 
![error](https://github.com/bhavik001/TxtToHTML/assets/132917653/babee083-8c38-413c-96fe-69227264b3ea)

**Comment by bhavik001** [comment]
Hello,
When you clone the repository please try running `npm install` command.
Then run `npm run start` command not `npm start`.
