### ISSUE TITLE
Issue 1 Quite difficult to run

### ISSUE THREAD

**Issue by rabroldan** [bhavik001/TxtToHTML#2]
Running the tool is not beginner friently, in order to run the program I had to open a code editor and run it through that terminal. I was unable to run it through a local machine aside for a code editor

**Comment by bhavik001** [comment]
Hello,
Thank you for reviewing this and give comment on this.
I think if you will share a screenshot for running both in terminal and vscode would be good.

**Comment by bhavik001** [comment]
Hello Again,
I have run the entire program in the local terminal and it is working.
I would make an update in the Readme.md file to make the new user conformable to use it.
