### ISSUE TITLE
Issue 3 - Output does not properly convert a single file

### ISSUE THREAD

**Issue by rabroldan** [bhavik001/TxtToHTML#4]
-o did work but if the file is located in the main folder it will duplicate the entire folder and now will have multiple repeating files, documents in the main directory it also throws an error if a folder is being converted

**Comment by bhavik001** [comment]
Hi,
Thank you for giving me feedback.
Can you share me the screenshots. Please

**Comment by rabroldan** [comment]
![image](https://github.com/bhavik001/TxtToHTML/assets/141264553/808685b4-de89-485e-be55-d8d18cca4d8b)

**Comment by rabroldan** [comment]
![image](https://github.com/bhavik001/TxtToHTML/assets/141264553/9eee758c-d1de-4a02-a916-88104be73e03)

I ended up with this

**Comment by bhavik001** [comment]
Hi,
I have make some changes in the code and you can check now its working.
Instead of -output use --output
Use 
```bash
node src/index.js <.txt file or floder name> --output <in the custom folder you want to save the files>
```
Let me know if it work for you So that I can close the issue.
