### ISSUE TITLE
Issue 4 - Missing Features Runtime conversion

### ISSUE THREAD

**Issue by rabroldan** [bhavik001/TxtToHTML#5]
This somehow relates to the program being beginner friendly, in order to successfuly run the program an entire process needs to be followed. A feature that would work wonders with thiis would be a possibility if the program runs and converts during runtime. the  page to open would be ideal once the convertion is completed.

**Comment by bhavik001** [comment]
Thank you for reviewing.
i know my program need many things beforehand to run. But this is the only way to run any JavaScript application locally.
Hope you fin this well.
