### ISSUE TITLE
Issue 5 - Visual Design Improvment

### ISSUE THREAD

**Issue by rabroldan** [bhavik001/TxtToHTML#6]
Another missing feature would be to improve the ability to add design to the converted html file. After opening the file manually it shows site with texts on it. Improvement in this end would be ideal.

**Comment by rabroldan** [comment]
The program works as intended though some features works better than others. it does not reflect the ability of the tool to perform its intended tasks

**Comment by bhavik001** [comment]
Hello,
Thank you for your feedback. But I have already implemented the 2 optional features. But would try to add the feature later on as we move forward.
